### ISSUE TITLE
Array render causes error

### ISSUE THREAD

**Issue by sukazavr** [eclipsesource/jsonforms#1509]
**Describe the bug**
I don't use Redux. When uischema includes array render It causes error:
```
browser.js:34 Uncaught Invariant Violation: Could not find "store" in the context of "Connect(Dispatch)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Dispatch) in connect options.
    at invariant (http://localhost:3000/static/js/0.chunk.js:81418:15)
    at ConnectFunction (http://localhost:3000/static/js/0.chunk.js:173210:55)
    at renderWithHooks (http://localhost:3000/static/js/0.chunk.js:156293:22)
    at updateFunctionComponent (http://localhost:3000/static/js/0.chunk.js:158177:24)
    at updateSimpleMemoComponent (http://localhost:3000/static/js/0.chunk.js:158117:14)
    at updateMemoComponent (http://localhost:3000/static/js/0.chunk.js:158022:18)
    at beginWork$1 (http://localhost:3000/static/js/0.chunk.js:159914:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/0.chunk.js:140835:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/0.chunk.js:140884:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/0.chunk.js:140938:35)
    at beginWork$$1 (http://localhost:3000/static/js/0.chunk.js:165042:11)
    at performUnitOfWork (http://localhost:3000/static/js/0.chunk.js:163974:16)
    at workLoopSync (http://localhost:3000/static/js/0.chunk.js:163952:26)
    at renderRoot (http://localhost:3000/static/js/0.chunk.js:163627:15)
    at runRootCallback (http://localhost:3000/static/js/0.chunk.js:163281:24)
    at http://localhost:3000/static/js/0.chunk.js:152358:28
    at unstable_runWithPriority (http://localhost:3000/static/js/0.chunk.js:195461:16)
    at runWithPriority$2 (http://localhost:3000/static/js/0.chunk.js:152306:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/0.chunk.js:152353:11)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/0.chunk.js:152341:7)
    at unbatchedUpdates (http://localhost:3000/static/js/0.chunk.js:163430:11)
    at legacyRenderSubtreeIntoContainer (http://localhost:3000/static/js/0.chunk.js:166841:9)
    at Object.render (http://localhost:3000/static/js/0.chunk.js:166932:16)
    at Module../src/index.tsx (http://localhost:3000/static/js/main.chunk.js:1798:50)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:786:30)
    at fn (http://localhost:3000/static/js/bundle.js:151:20)
    at Object.0 (http://localhost:3000/static/js/main.chunk.js:4034:18)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:786:30)
    at checkDeferredModules (http://localhost:3000/static/js/bundle.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://localhost:3000/static/js/bundle.js:33:19)
    at http://localhost:3000/static/js/main.chunk.js:1:101

index.js:1375 The above error occurred in the <ConnectFunction> component:
    in ConnectFunction (created by NonEmptyCell)
    in td (created by ForwardRef(TableCell))
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
    in WithStyles(ForwardRef(TableCell)) (created by NoBorderTableCell)
    in NoBorderTableCell (created by WithStyles(NoBorderTableCell))
    in WithStyles(NoBorderTableCell) (created by NonEmptyCell)
    in NonEmptyCell
    in tr (created by ForwardRef(TableRow))
    in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
    in WithStyles(ForwardRef(TableRow))
    in Unknown (created by TableRows)
    in TableRows (created by MaterialTableControl)
    in tbody (created by ForwardRef(TableBody))
    in ForwardRef(TableBody) (created by WithStyles(ForwardRef(TableBody)))
    in WithStyles(ForwardRef(TableBody)) (created by MaterialTableControl)
    in table (created by ForwardRef(Table))
    in ForwardRef(Table) (created by WithStyles(ForwardRef(Table)))
    in WithStyles(ForwardRef(Table)) (created by MaterialTableControl)
    in HiddenJs (created by WithWidth(HiddenJs))
    in WithWidth(HiddenJs) (created by Hidden)
    in Hidden (created by MaterialTableControl)
    in MaterialTableControl
    in HiddenJs (created by WithWidth(HiddenJs))
    in WithWidth(HiddenJs) (created by Hidden)
    in Hidden
    in Unknown
    in Unknown (created by Component)
    in Component (created by Component)
    in Component (created by JsonFormsDispatchRenderer)
    in JsonFormsDispatchRenderer
    in Unknown
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid))
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid))
    in HiddenJs (created by WithWidth(HiddenJs))
    in WithWidth(HiddenJs) (created by Hidden)
    in Hidden
    in Unknown
    in Unknown
    in Unknown
    in Unknown (created by Component)
    in Component (created by Component)
    in Component (created by JsonFormsDispatchRenderer)
    in JsonFormsDispatchRenderer
    in Unknown (created by Component)
    in Component (created by Component)
    in Component (at Shell.tsx:25)
    in ThemeProvider (at Shell.tsx:17)
    in Shell (created by HotExportedShell)
    in AppContainer (created by HotExportedShell)
    in HotExportedShell (at src/index.tsx:7)

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```

**To Reproduce**
1. Use React component like this:
```
<JsonForms
  schema={{
    type: "object",
    properties: {
      name: {
        type: "string"
      },
      authors: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: {
              type: "string"
            },
            url: {
              type: "string"
            }
          },
          required: ["name"]
        }
      }
    }
  }}
  uischema={
    {
      type: "VerticalLayout",
      elements: [
        {
          type: "Control",
          scope: "#/properties/name"
        },
        {
          type: "Control",
          scope: "#/properties/authors"
        }
      ]
    } as any
  }
  data={{
    name: "John Doe",
    authors: [{ name: "FF" }, { name: "FFD", url: "dfdf" }]
  }}
  renderers={materialRenderers}
  onChange={actionsFormGeneral.change}
/>
```
2. Get an error

**Expected behavior**
Render array list.

**Browser (please complete the following information):**
Google Chrome
Version 77.0.3865.90 (Official Build) (64-bit)

**Used Setup (please complete the following information):**
 - Framework: React without Redux
 - RendererSet: material

**Additional context**
If you comment description about array rendering in uischema, you will get working example.

    "@jsonforms/core": "^2.3.1-beta.0"
    "@jsonforms/material-renderers": "^2.3.1-beta.0"
    "@jsonforms/react": "^2.3.1-beta.0"
    "@material-ui/core": "^4.5.0"
    "@material-ui/icons": "^4.4.3"

**Comment by edgarmueller** [comment]
Thanks for the report, we'll try to address this for 2.3.2
