### ISSUE TITLE
Error when using material renderers

### ISSUE THREAD

**Issue by mattcopas** [eclipsesource/jsonforms#1550]
**Describe the bug**
I get an error when using `materialRenderers`:

```
Error: Spacing 7 invalid, must be between 0 and 6 inclusive
    at spacing (http://localhost:9009/vendors~main.80747ef6b0c28089f2d0.bundle.js:2033:15)
    at Object.spacing (http://localhost:9009/vendors~main.80747ef6b0c28089f2d0.bundle.js:50485:14)
    at http://localhost:9009/vendors~main.80747ef6b0c28089f2d0.bundle.js:27367:30
    at Array.forEach (<anonymous>)
    at generateGutter (http://localhost:9009/vendors~main.80747ef6b0c28089f2d0.bundle.js:27366:12)
    at styles (http://localhost:9009/vendors~main.80747ef6b0c28089f2d0.bundle.js:27509:6)
    at Object.create (http://localhost:9009/vendors~main.80747ef6b0c28089f2d0.bundle.js:195759:35)
    at attach (http://localhost:9009/vendors~main.80747ef6b0c28089f2d0.bundle.js:196202:32)
    at http://localhost:9009/vendors~main.80747ef6b0c28089f2d0.bundle.js:196343:7
    at useSynchronousEffect (http://localhost:9009/vendors~main.80747ef6b0c28089f2d0.bundle.js:196296:14)
```

**To Reproduce**
```jsx
  import { person } from '@jsonforms/examples'
  import { materialRenderers } from '@jsonforms/material-renderers'
  import { JsonForms } from '@jsonforms/react'
  const { schema, uischema, data } = person
    <JsonForms
      cells={materialCells}
      schema={schema}
      uischema={uischema}
      data={data}
      renderers={materialRenderers}
    />
```
**Expected behavior**
A form to be rendered, with a material look, based on your person example

**Browser (please complete the following information):**
 - Browser Chrome
 - Version 80

**Used Setup (please complete the following information):**
 - Framework: React  16.12
 - RendererSet: materialRenderers

This is being rendered in Storybook - but all my other components work fine, so I doubt it's that

**Comment by mattcopas** [comment]
My mistake - this was caused by our theme provider

**Comment by sdirix** [comment]
No problem! Thanks for your interest in JSON Forms ;)
