### ISSUE TITLE
Support for Angular 10 & 11

### ISSUE THREAD

**Issue by nene** [eclipsesource/jsonforms#1745]
I was looking at adopting JSONForms in my app, but discovered that only Angular 9 is supported, although the latest Angular release is already 11. 

**Proposal:**
- Upgrade to Angular 10, release new version of jsonforms/angular.
- Upgrade to Angular 11, do another release.
(I think it's important to do releases for both 10 and 11, so anybody currently using 9 with jsonforms can successfully perform upgrade to Angular 10 v/s going directly to 11, which might not be an option to everybody. Plus the Angular own guideline is to upgrade one version at the time.)

Framework: [angular]
RendererSet: [vanilla]

**Comment by sdirix** [comment]
Hi @nene, we would happily accept a contribution, updating to Angular 10 or 11.

The first step would be to just do the update and check whether any problems occur. If you can confirm that there are none for your use cases, or even fix the problems you found, then this will help us to migrate to these Angular versions sooner.

**Comment by nene** [comment]
I started to look into this, but things have turned out more complicated than I initially expected.

For example:

- Angular 10 wants TypeScript >= 3.9, which I guess will affect all other jsonforms packages as well.
- It also suggests upgrading TSLint to v6, but that won't play along nicely with tslint-react, which only supports v5 (I suppose tslint-react might have been abandoned as TSLint itself has also been deprecated in favor of using ESLint).
- Looks like one can't use the standard `ng update` command in this repository structure, so lots of stuff needs to be done manually.

I tried to fight through these problems, but failed. Ending up with a mystery error with building jsonforms/vue:

```
> jsonforms-monorepo@ build /Users/nene/github/jsonforms
> lerna run build && lerna run doc

lerna notice cli v3.22.1
lerna info Executing command in 13 packages: "npm run build"
lerna info run Ran npm script 'build' in '@jsonforms/core' in 2.6s:

> @jsonforms/core@2.5.1-beta.0 build /Users/nene/github/jsonforms/packages/core
> tsc

lerna ERR! npm run build exited 1 in '@jsonforms/vue'
lerna ERR! npm run build stdout:

> @jsonforms/vue@2.5.1-beta.0 build /Users/nene/github/jsonforms/packages/vue/vue
> cross-env NODE_ENV=production rollup --config rollup.config.js


lerna ERR! npm run build stderr:
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn rollup ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn rollup',
  path: 'rollup',
  spawnargs: [ '--config', 'rollup.config.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @jsonforms/vue@2.5.1-beta.0 build: `cross-env NODE_ENV=production rollup --config rollup.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @jsonforms/vue@2.5.1-beta.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nene/.npm/_logs/2021-05-03T12_59_08_678Z-debug.log
```

I'm on the territory where I have no idea what I'm doing. So I'm probably giving up on this :(

**Comment by sdirix** [comment]
Yes we plan to replace tslint with ESLint soon :+1:

Thanks for trying! Yes getting all of these technologies play nicely together in one mono repo is not that easy :/. We'll also take a look at upgrading Angular soonish.

In general you might be interested in our [professional support offerings](https://jsonforms.io/support). So if you're for example interested in always up to date Angular bindings, we could prioritize that and work with your schedule.

**Comment by eneufeld** [comment]
Hi @nene, 

I checked our seed: https://github.com/eclipsesource/jsonforms-angular-seed 
It is already running Angular 10. Yes you get some warnings but it works in general.
I also added a PR for Angular 11: https://github.com/eclipsesource/jsonforms-angular-seed/pull/23
It seems to work without issues.

Of course we should upgrade JSONForms to Angular 11 but with the 6 month release schedule of Angular I'm wondering whether it makes sense upgrade our minimal requirements versions at the same rate.
I would suggest to change the Angular version to >9.0.0 and check the seed regulary.
@sdirix what is your take on this?

Best,
Eugen
