### ISSUE TITLE
Stepper Variant React Error when using Navigation Elements

### ISSUE THREAD

**Issue by osseonews** [eclipsesource/jsonforms#2362]
### Describe the bug

When we try to implement the Stepper Example here: https://jsonforms.io/examples/categorization#stepper-variant-with-navigation-elements, when we click on the option, "Provide Address", React throws the following error:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `MaterialCategorizationStepperLayoutRenderer`. See https://reactjs.org/link/warning-keys for more information.
    at Step (webpack-internal:///./node_modules/@mui/material/Step/Step.js:68:87)
    at MaterialCategorizationStepperLayoutRenderer (webpack-internal:///./node_modules/@jsonforms/material-renderers/lib/jsonforms-react-material.esm.js:1650:96)
    at WithContextToLayoutProps (webpack-internal:///./node_modules/@jsonforms/react/lib/jsonforms-react.esm.js:275:85)
    at WithJsonFormsContext (webpack-internal:///./node_modules/@jsonforms/react/lib/jsonforms-react.esm.js:263:17)
    at WithTranslateProps (webpack-internal:///./node_modules/@jsonforms/react/lib/jsonforms-react.esm.js:370:17)
    at WithAjvProps (webpack-internal:///./node_modules/@jsonforms/material-renderers/lib/jsonforms-react-material.esm.js:639:79)
    at TestAndRender (webpack-internal:///./node_modules/@jsonforms/react/lib/jsonforms-react.esm.js:409:16)
    at JsonFormsDispatchRenderer (webpack-internal:///./node_modules/@jsonforms/react/lib/jsonforms-react.esm.js:378:9)
    at WithContextToJsonFormsRendererProps (webpack-internal:///./node_modules/@jsonforms/react/lib/jsonforms-react.esm.js:266:107)
    at WithJsonFormsContext (webpack-internal:///./node_modules/@jsonforms/react/lib/jsonforms-react.esm.js:263:17)
    at JsonFormsStateProvider (webpack-internal:///./node_modules/@jsonforms/react/lib/jsonforms-react.esm.js:132:35)
    at JsonForms (webpack-internal:///./node_modules/@jsonforms/react/lib/jsonforms-react.esm.js:428:13)
    at form
    at div
```

### Expected behavior

There should be a unique key. It's not clear where the error is coming from. Probably something in the schema for the address? We couldn't locate where the error was coming from.

### Steps to reproduce the issue

1. Install the schema and uischema for the example here: https://jsonforms.io/examples/categorization#stepper-variant-with-navigation-elements and run it in React

### Which Version of JSON Forms are you using?

3.3.0

### Framework

React

### RendererSet

Material

**Comment by osseonews** [comment]
I'm thinking the bug is because the UI Schema for address is missing the label? It has "type": "Category",
      "i18n": "address", and there should be a "label"? I'm not totally familiar with this library yet. But maybe that's the solution.

**Comment by sdirix** [comment]
Hi @osseonews,

correct. The stepper renderer uses the label as the `key`, see [here](https://github.com/eclipsesource/jsonforms/blob/3a32f03c3eda311d8d8690293c6e63ec20927d87/packages/material-renderers/src/layouts/MaterialCategorizationStepperLayout.tsx#L135).
